
type Product{
    id:ID
    name : String
    createdAt : String 
    grades : [Grades]
    unitWeight : Float
}

type Query{
    getProduct(id:ID!) : Product
    getProductByName(name:String!) : Product
    getAllProducts : [Product]
}

type Mutation{
    addProduct(name:String!, unitWeight : Float , grades : [GradesInput]) : Boolean
    updateProduct(id:ID!, name:String, unitWeight : Float , grades : [GradesInput]) : Boolean
    deleteProduct(id:ID!) : Boolean
}
